// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Character struct {
	Name      string   `json:"name"`
	Cines     []string `json:"cines,omitempty"`
	StarShips []string `json:"starShips,omitempty"`
}

type CharacterFilterInput struct {
	Name string `json:"name"`
}

type CharacterInput struct {
	Name       string   `json:"name"`
	Cines      []string `json:"cines,omitempty"`
	StartShips []string `json:"startShips,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type SaveSearchInput struct {
	Characters []*CharacterInput `json:"characters"`
}
